import type { Metadata } from "next";
import "./global.css";
import { Navbar } from "@/components/layout/Navbar"; // Double check this path matches your file structure

export const metadata: Metadata = {
  title: "My MVP",
  description: "Generated by BoilerplateAI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Navbar must be INSIDE the body */}
      <body className="min-h-screen bg-background font-sans antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
